# Generated by Django 5.2.4 on 2025-07-31 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mesoregion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImmediateRegion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('intermediate_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immediate_regions', to='regions.intermediateregion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Microregion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mesoregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microregion', to='regions.mesoregion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('immediate_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='regions.immediateregion')),
                ('microregion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='regions.microregion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('municipaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='regions.municipality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=2)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='regions.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mesoregion',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesoregions', to='regions.state'),
        ),
        migrations.AddField(
            model_name='intermediateregion',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_regions', to='regions.state'),
        ),
    ]
