# Generated by Django 5.2.4 on 2025-07-31 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_municipality_microregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='municipaly',
            new_name='municipality',
        ),
        migrations.AlterField(
            model_name='microregion',
            name='mesoregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microregions', to='regions.mesoregion'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='immediate_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='regions.immediateregion'),
        ),
    ]
