# Generated by Django 5.2.4 on 2025-08-02 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('legal_nature', models.CharField(max_length=4)),
                ('qualification', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('size', models.CharField(choices=[('00', 'Not Informed'), ('01', 'Micro Company'), ('03', 'Small Company'), ('05', 'Other')], max_length=2)),
                ('federative_entity', models.CharField(max_length=30)),
            ],
        ),
    ]
