# Generated by Django 5.2.4 on 2025-08-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='federative_entity',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(blank=True, choices=[('00', 'Not Informed'), ('01', 'Micro Company'), ('03', 'Small Company'), ('05', 'Other')], max_length=2, null=True),
        ),
    ]
